// This file is auto-generated by build.rs
pub mod day3;
pub mod day7;
pub mod day6;
pub mod day2;
pub mod day5;
pub mod day1;
pub mod day4;
mod day7_test_util;
pub mod day8;
pub mod day9;
pub mod day10;
